[package]
name = "exmaple-plugin-primop"
edition = "2024"

[dependencies]
libc = "0.2.174"
nix-exprc-sys = { path = "../../nix-exprc-sys", features = ["shared"] }

[lib]
name = "increment"
crate-type = ["rlib", "cdylib"]